<?php
/**
 * Created by PhpStorm.
 * User: whis
 * Date: 3/28/17
 * Time: 6:15 PM
 */
namespace app\controllers;

use app\components\DXLog;
use app\components\DXUtil;
use dix\base\controller\BaseController;
use GuzzleHttp\Client;

class NotifyController extends BaseController 
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
    }

    public function actionDo()
    {
        $requestBody = app()->getRequest()->getRawBody();

        if (!$requestBody)
        {
            $this->finishSuccess(null);
        }

        $url = "http://sc.ftqq.com/SCU6349T23ce526185f836b02508e20b7b80f83e58b95e2a4234a.send";
        $client = new Client();

        $request_data = [
            'text' => "Docker构建",
            'desp' => "`${requestBody}`"
        ];
        $res = $client->post($url, [
            'form_params' => $request_data
        ]);

        $response = @json_decode('' . $res->getBody(), true);

        \Yii::error(DXUtil::jsonEncode($response));
        $this->finishSuccess($response);
    }
}